version: 1
builder:
  configs:
    - platform: ios
      documentation_targets: ["DatadogInternalLegacy", "DatadogCoreLegacy", "DatadogObjc", "DatadogLogsLegacy", "DatadogTrace", "DatadogRUM", "DatadogSessionReplay", "DatadogCrashReporting", "DatadogWebViewTracking"]
